package model;

// Generated 11.06.2012 19:20:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContactType generated by hbm2java
 */
@Entity
@Table(name = "contact_type")
public class ContactType implements java.io.Serializable {

	private int contactType;
	private String typeName;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public ContactType() {
	}

	public ContactType(int contactType) {
		this.contactType = contactType;
	}

	public ContactType(int contactType, String typeName, Set<Contact> contacts) {
		this.contactType = contactType;
		this.typeName = typeName;
		this.contacts = contacts;
	}

	@Id
	@Column(name = "contact_type", unique = true, nullable = false)
	public int getContactType() {
		return this.contactType;
	}

	public void setContactType(int contactType) {
		this.contactType = contactType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactType")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
