package model;

// Generated 12.06.2012 19:50:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact")
public class Contact implements java.io.Serializable {

	private int contact;
	private ContactType contactType;
	private SubjectType subjectType;
	private Integer subjectFk;
	private String valueText;
	private Integer orderby;
	private String note;

	public Contact() {
	}

	public Contact(int contact) {
		this.contact = contact;
	}

	public Contact(int contact, ContactType contactType,
			SubjectType subjectType, Integer subjectFk, String valueText,
			Integer orderby, String note) {
		this.contact = contact;
		this.contactType = contactType;
		this.subjectType = subjectType;
		this.subjectFk = subjectFk;
		this.valueText = valueText;
		this.orderby = orderby;
		this.note = note;
	}

	@Id
	@Column(name = "contact", unique = true, nullable = false)
	public int getContact() {
		return this.contact;
	}

	public void setContact(int contact) {
		this.contact = contact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_type_fk")
	public ContactType getContactType() {
		return this.contactType;
	}

	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_type_fk")
	public SubjectType getSubjectType() {
		return this.subjectType;
	}

	public void setSubjectType(SubjectType subjectType) {
		this.subjectType = subjectType;
	}

	@Column(name = "subject_fk")
	public Integer getSubjectFk() {
		return this.subjectFk;
	}

	public void setSubjectFk(Integer subjectFk) {
		this.subjectFk = subjectFk;
	}

	@Column(name = "value_text")
	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	@Column(name = "orderby")
	public Integer getOrderby() {
		return this.orderby;
	}

	public void setOrderby(Integer orderby) {
		this.orderby = orderby;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
