package model;

// Generated 12.06.2012 19:50:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerPriceList generated by hbm2java
 */
@Entity
@Table(name = "customer_price_list")
public class CustomerPriceList implements java.io.Serializable {

	private long customerPriceList;
	private PriceList priceList;
	private Customer customer;

	public CustomerPriceList() {
	}

	public CustomerPriceList(long customerPriceList) {
		this.customerPriceList = customerPriceList;
	}

	public CustomerPriceList(long customerPriceList, PriceList priceList,
			Customer customer) {
		this.customerPriceList = customerPriceList;
		this.priceList = priceList;
		this.customer = customer;
	}

	@Id
	@Column(name = "customer_price_list", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCustomerPriceList() {
		return this.customerPriceList;
	}

	public void setCustomerPriceList(long customerPriceList) {
		this.customerPriceList = customerPriceList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "price_list_fk")
	public PriceList getPriceList() {
		return this.priceList;
	}

	public void setPriceList(PriceList priceList) {
		this.priceList = priceList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_fk")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

}
