package model;

// Generated 12.06.2012 19:50:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeRole generated by hbm2java
 */
@Entity
@Table(name = "employee_role")
public class EmployeeRole implements java.io.Serializable {

	private int employeeRole;
	private Employee employee;
	private EmployeeRoleType employeeRoleType;
	private String active;

	public EmployeeRole() {
	}

	public EmployeeRole(int employeeRole) {
		this.employeeRole = employeeRole;
	}

	public EmployeeRole(int employeeRole, Employee employee,
			EmployeeRoleType employeeRoleType, String active) {
		this.employeeRole = employeeRole;
		this.employee = employee;
		this.employeeRoleType = employeeRoleType;
		this.active = active;
	}

	@Id
	@Column(name = "employee_role", unique = true, nullable = false)
	public int getEmployeeRole() {
		return this.employeeRole;
	}

	public void setEmployeeRole(int employeeRole) {
		this.employeeRole = employeeRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_fk")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_role_type_fk")
	public EmployeeRoleType getEmployeeRoleType() {
		return this.employeeRoleType;
	}

	public void setEmployeeRoleType(EmployeeRoleType employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	@Column(name = "active", length = 1)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

}
