package model;

// Generated 11.06.2012 19:20:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StructUnit generated by hbm2java
 */
@Entity
@Table(name = "struct_unit")
public class StructUnit implements java.io.Serializable {

	private int structUnit;
	private Integer enterpriseFk;
	private Integer upperUnitFk;
	private Integer level;
	private String name;

	public StructUnit() {
	}

	public StructUnit(int structUnit) {
		this.structUnit = structUnit;
	}

	public StructUnit(int structUnit, Integer enterpriseFk,
			Integer upperUnitFk, Integer level, String name) {
		this.structUnit = structUnit;
		this.enterpriseFk = enterpriseFk;
		this.upperUnitFk = upperUnitFk;
		this.level = level;
		this.name = name;
	}

	@Id
	@Column(name = "struct_unit", unique = true, nullable = false)
	public int getStructUnit() {
		return this.structUnit;
	}

	public void setStructUnit(int structUnit) {
		this.structUnit = structUnit;
	}

	@Column(name = "enterprise_fk")
	public Integer getEnterpriseFk() {
		return this.enterpriseFk;
	}

	public void setEnterpriseFk(Integer enterpriseFk) {
		this.enterpriseFk = enterpriseFk;
	}

	@Column(name = "upper_unit_fk")
	public Integer getUpperUnitFk() {
		return this.upperUnitFk;
	}

	public void setUpperUnitFk(Integer upperUnitFk) {
		this.upperUnitFk = upperUnitFk;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
