package ladu.model;

// Generated 12.06.2012 19:50:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EntPerRelationType generated by hbm2java
 */
@Entity
@Table(name = "ent_per_relation_type")
public class EntPerRelationType implements java.io.Serializable {

	private int entPerRelationType;
	private String typeName;
	private Set<EnterprisePersonRelation> enterprisePersonRelations = new HashSet<EnterprisePersonRelation>(
			0);

	public EntPerRelationType() {
	}

	public EntPerRelationType(int entPerRelationType) {
		this.entPerRelationType = entPerRelationType;
	}

	public EntPerRelationType(int entPerRelationType, String typeName,
			Set<EnterprisePersonRelation> enterprisePersonRelations) {
		this.entPerRelationType = entPerRelationType;
		this.typeName = typeName;
		this.enterprisePersonRelations = enterprisePersonRelations;
	}

	@Id
	@Column(name = "ent_per_relation_type", unique = true, nullable = false)
	public int getEntPerRelationType() {
		return this.entPerRelationType;
	}

	public void setEntPerRelationType(int entPerRelationType) {
		this.entPerRelationType = entPerRelationType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entPerRelationType")
	public Set<EnterprisePersonRelation> getEnterprisePersonRelations() {
		return this.enterprisePersonRelations;
	}

	public void setEnterprisePersonRelations(
			Set<EnterprisePersonRelation> enterprisePersonRelations) {
		this.enterprisePersonRelations = enterprisePersonRelations;
	}

}
