package ladu.model;

// Generated 12.06.2012 19:50:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TypeAttribute generated by hbm2java
 */
@Entity
@Table(name = "type_attribute")
public class TypeAttribute implements java.io.Serializable {

	private long typeAttribute;
	private ItemType itemType;
	private ItemAttributeType itemAttributeType;
	private Long orderby;
	private String required;
	private String createdByDefault;

	public TypeAttribute() {
	}

	public TypeAttribute(long typeAttribute) {
		this.typeAttribute = typeAttribute;
	}

	public TypeAttribute(long typeAttribute, ItemType itemType,
			ItemAttributeType itemAttributeType, Long orderby, String required,
			String createdByDefault) {
		this.typeAttribute = typeAttribute;
		this.itemType = itemType;
		this.itemAttributeType = itemAttributeType;
		this.orderby = orderby;
		this.required = required;
		this.createdByDefault = createdByDefault;
	}

	@Id
	@Column(name = "type_attribute", unique = true, nullable = false, precision = 10, scale = 0)
	public long getTypeAttribute() {
		return this.typeAttribute;
	}

	public void setTypeAttribute(long typeAttribute) {
		this.typeAttribute = typeAttribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_type_fk")
	public ItemType getItemType() {
		return this.itemType;
	}

	public void setItemType(ItemType itemType) {
		this.itemType = itemType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_attribute_type_fk")
	public ItemAttributeType getItemAttributeType() {
		return this.itemAttributeType;
	}

	public void setItemAttributeType(ItemAttributeType itemAttributeType) {
		this.itemAttributeType = itemAttributeType;
	}

	@Column(name = "orderby", precision = 10, scale = 0)
	public Long getOrderby() {
		return this.orderby;
	}

	public void setOrderby(Long orderby) {
		this.orderby = orderby;
	}

	@Column(name = "required", length = 1)
	public String getRequired() {
		return this.required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

	@Column(name = "created_by_default", length = 1)
	public String getCreatedByDefault() {
		return this.createdByDefault;
	}

	public void setCreatedByDefault(String createdByDefault) {
		this.createdByDefault = createdByDefault;
	}

}
