package ladu.model;

// Generated 12.06.2012 19:50:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemActionType generated by hbm2java
 */
@Entity
@Table(name = "item_action_type")
public class ItemActionType implements java.io.Serializable {

	private long itemActionType;
	private String typeName;
	private Set<ItemAction> itemActions = new HashSet<ItemAction>(0);

	public ItemActionType() {
	}

	public ItemActionType(long itemActionType) {
		this.itemActionType = itemActionType;
	}

	public ItemActionType(long itemActionType, String typeName,
			Set<ItemAction> itemActions) {
		this.itemActionType = itemActionType;
		this.typeName = typeName;
		this.itemActions = itemActions;
	}

	@Id
	@Column(name = "item_action_type", unique = true, nullable = false, precision = 10, scale = 0)
	public long getItemActionType() {
		return this.itemActionType;
	}

	public void setItemActionType(long itemActionType) {
		this.itemActionType = itemActionType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemActionType")
	public Set<ItemAction> getItemActions() {
		return this.itemActions;
	}

	public void setItemActions(Set<ItemAction> itemActions) {
		this.itemActions = itemActions;
	}

}
