package model;

// Generated 11.06.2012 19:20:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubjectAttributeType generated by hbm2java
 */
@Entity
@Table(name = "subject_attribute_type")
public class SubjectAttributeType implements java.io.Serializable {

	private int subjectAttributeType;
	private SubjectType subjectType;
	private String typeName;
	private Integer dataType;
	private Integer orderby;
	private String required;
	private String multipleAttributes;
	private String createdByDefault;
	private Set<SubjectAttribute> subjectAttributes = new HashSet<SubjectAttribute>(
			0);

	public SubjectAttributeType() {
	}

	public SubjectAttributeType(int subjectAttributeType) {
		this.subjectAttributeType = subjectAttributeType;
	}

	public SubjectAttributeType(int subjectAttributeType,
			SubjectType subjectType, String typeName, Integer dataType,
			Integer orderby, String required, String multipleAttributes,
			String createdByDefault, Set<SubjectAttribute> subjectAttributes) {
		this.subjectAttributeType = subjectAttributeType;
		this.subjectType = subjectType;
		this.typeName = typeName;
		this.dataType = dataType;
		this.orderby = orderby;
		this.required = required;
		this.multipleAttributes = multipleAttributes;
		this.createdByDefault = createdByDefault;
		this.subjectAttributes = subjectAttributes;
	}

	@Id
	@Column(name = "subject_attribute_type", unique = true, nullable = false)
	public int getSubjectAttributeType() {
		return this.subjectAttributeType;
	}

	public void setSubjectAttributeType(int subjectAttributeType) {
		this.subjectAttributeType = subjectAttributeType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_type_fk")
	public SubjectType getSubjectType() {
		return this.subjectType;
	}

	public void setSubjectType(SubjectType subjectType) {
		this.subjectType = subjectType;
	}

	@Column(name = "type_name", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "data_type")
	public Integer getDataType() {
		return this.dataType;
	}

	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}

	@Column(name = "orderby")
	public Integer getOrderby() {
		return this.orderby;
	}

	public void setOrderby(Integer orderby) {
		this.orderby = orderby;
	}

	@Column(name = "required", length = 1)
	public String getRequired() {
		return this.required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

	@Column(name = "multiple_attributes", length = 1)
	public String getMultipleAttributes() {
		return this.multipleAttributes;
	}

	public void setMultipleAttributes(String multipleAttributes) {
		this.multipleAttributes = multipleAttributes;
	}

	@Column(name = "created_by_default", length = 1)
	public String getCreatedByDefault() {
		return this.createdByDefault;
	}

	public void setCreatedByDefault(String createdByDefault) {
		this.createdByDefault = createdByDefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjectAttributeType")
	public Set<SubjectAttribute> getSubjectAttributes() {
		return this.subjectAttributes;
	}

	public void setSubjectAttributes(Set<SubjectAttribute> subjectAttributes) {
		this.subjectAttributes = subjectAttributes;
	}

}
